// "Build fingerprint": one hash over every file the server runs (code, pages, translations, package.json).
// If even one character changes anywhere, the fingerprint changes. Shown in the admin panel and /readyz,
// so the owner can compare it with the fingerprint given with each release.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
// package-lock.json is generated by npm install on the server, so it is not part of the fingerprint.
const PARTS = ['src', 'public', 'admin-ui', 'locales', 'scripts', 'package.json'];

function walk(p, out) {
  let st; try { st = statSync(p); } catch { return; }
  if (st.isDirectory()) for (const f of readdirSync(p)) walk(join(p, f), out);
  else out.push(p);
}

export function computeFingerprint(root = ROOT) {
  const files = [];
  for (const part of PARTS) walk(join(root, part), files);
  files.sort();
  const h = createHash('sha256');
  for (const f of files) {
    h.update(relative(root, f).split('\\').join('/'));
    h.update('\0');
    h.update(readFileSync(f));
    h.update('\0');
  }
  const hex = h.digest('hex').slice(0, 16).toUpperCase();
  return { fingerprint: hex.match(/.{4}/g).join('-'), files: files.length };
}
